name: ci-cd-pipeline
run-name: ${{ github.actor }} is learning GitHub Actions
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - name
jobs:
    build-image:
        runs-on: ubuntu-latest
        steps:
            # We need to check out the code from github.
            - uses: actions/checkout@v5
